config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "static_pages#home"
  get "/terms", to: "static_pages#terms"
  get "/privacy", to: "static_pages#privacy"
  get "users/new", to: "users#new", as: "new_users"
  post "users", to: "users#submit", as: "submit_users"
  get "users/result/:id", to: "users#result", as: "result"
  get "images/ogp.png", to: "images#ogp", as: "images_ogp"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/national_day.rb
class NationalDay < ApplicationRecord
    validates :country_name, :national_day, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 255 }
  validates :birth_month, :birth_day, presence: true
  validates :birth_month, inclusion: { in: 1..12 }
  validates :birth_day, inclusion: { in: 1..31 }

  def find_closest_national_day
    birth_month_day = Date.new(2000, birth_month, birth_day)

    NationalDay
      # ±3日以内の記念日をDBにて取得
      .where("ABS(EXTRACT(DOY FROM national_day) - EXTRACT(DOY FROM CAST(? AS DATE))) <= 3", birth_month_day)
      .order(Arel.sql("ABS(EXTRACT(DOY FROM national_day) - EXTRACT(DOY FROM CAST('#{birth_month_day}' AS DATE))) ASC"))
      .first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :danger
  # add_flash_types とは、
  # フラッシュメッセージのタイプを追加するメソッド
end

app/controllers/concerns/ogp_creator.rb
class OgpCreator
    require "mini_magick"
    BASE_IMAGE_PATH = "./app/assets/images/ogp.png"  # 実際の画像ファイル名に変更
    GRAVITY = "center"
    TEXT_POSITION = "0,-50" # 国名を少し上に配置
    TEXT_POSITION_DESCRIPTION = "0,50" # 記念日の説明を少し下に配置
    FONT = "./app/assets/fonts/RocknRollOne-Regular.ttf" # 使用するフォントのパス
    FONT_SIZE = 80
    FONT_SIZE_DESCRIPTION = 30 # 記念日の説明のフォントの大きさは30に変更
    INDENTION_COUNT = 16
    ROW_LIMIT = 8

    def self.build(text)
      texts = text.split("\n") # 1行目: 国名, 2行目: 記念日
      country_text = prepare_text(texts[0])
      description_text = texts[1] || ""
      image = MiniMagick::Image.open(BASE_IMAGE_PATH)
      image.combine_options do |config|
        config.font FONT
        config.fill "orange"
        config.gravity GRAVITY
        config.pointsize FONT_SIZE
        config.draw "text #{TEXT_POSITION} '#{country_text}'" # 　国名
        config.pointsize FONT_SIZE_DESCRIPTION # 記念日の説明フォントサイズを変更を反映させる
        config.draw "text #{TEXT_POSITION_DESCRIPTION} '#{description_text}'" # 記念日の名前
      end
    end

    private
    def self.prepare_text(text)
      text.to_s.scan(/.{1,#{INDENTION_COUNT}}/)[0...ROW_LIMIT].join("\n")
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  skip_before_action :require_login, raise: false
  def ogp
    text = ogp_params[:text]
    # 画像に表示させたいテキストを取得
    image = OgpCreator.build(text).tempfile.open.read
    # OgpCreatorが表示させたいテキストを追加した画像を作成
    # それをblobという形式で取得
    send_data image, type: "image/png", disposition: "inline"
    # blob形式の画像をpngファイルとして、レンダリング
  end
  private
  def ogp_params
    params.permit(:text)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home; end
    def terms; end
    def privacy; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new; end

  def submit
    @user = User.new(user_params)
    if @user.save
      redirect_to result_path(id: @user.id)
    else
      redirect_to new_users_path, danger: "名前が記載されているのを確認してください"
    end
  end

  def result
    @user = User.find(params[:id])
    @national_day = @user.find_closest_national_day

    # OGP画像のテキスト（国名 + 記念日の日付）
    ogp_text = @national_day.present? ? "#{@national_day.country_name}\n#{@national_day.description}" : "該当なし"

    # 動的OGP画像のURL
    ogp_image = @national_day.present? ? ogp_image_url(ogp_text) : default_ogp_image_url

    # metaタグの設定
    set_meta_tags(
      title: "#{@user.name}さんの誕生日に近い国の誕生日",
      description: @national_day.present? ? "#{@national_day.country_name}の#{@national_day.description}です！" : "私の誕生日に近い国の誕生日は見つかりませんでした。",
      og: {
        title: "#{@user.name}さんの誕生日に近い国の誕生日",
        description: @national_day.present? ? "#{@national_day.country_name}の#{@national_day.description}です！" : "私の誕生日に近い国の誕生日は見つかりませんでした。",
        image: ogp_image,
        url: request.original_url,
        type: "website"
      },
      twitter: {
        card: "summary_large_image",
        title: "#{@user.name}さんの誕生日に近い国の誕生日",
        description: @national_day.present? ? "#{@national_day.country_name}の#{@national_day.description}です！" : "私の誕生日に近い国の誕生日は見つかりませんでした。",
        image: ogp_image
      }
    )
  end


  private

  def ogp_image_url(text)
    images_ogp_url(text: text)
  end

  def default_ogp_image_url
    ActionController::Base.helpers.asset_path("default_ogp.png")
  end

  def user_params
    params.require(:user).permit(:name, :birth_month, :birth_day)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "BirthNation" %></title>
    <% if Rails.env.production? %>
      <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-6P48KF29W9"></script>
    <script>
     window.dataLayer = window.dataLayer || [];
     function gtag(){dataLayer.push(arguments);}
     gtag('js', new Date());

     gtag('config', 'G-6P48KF29W9');
    </script>
    <% end %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <%= favicon_link_tag("favicon.ico") %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <script src="https://kit.fontawesome.com/ed5990692e.js" crossorigin="anonymous"></script>
    <%= display_meta_tags %>
  </head>

  <body class="bg-[url('bg_image.png')] bg-cover bg-center">
    <div class="flex flex-col min-h-screen ">
    <%= render 'shared/header' %>
    <%= render 'shared/flash_message' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
    <div class="bg-red-300 text-white font-bold px-4 py-2" role="alert alert-<%= message_type %> ">
      <%= message %>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CSS Embed Example</title>
    <style>
        footer {
            position: sticky;
            top: 100vh;
            width: 100%;
            background: #44aa33;
        }
    </style>
</head>
<body>
    <footer class="bg-rose-200 h-12 flex items-center">
     <div class="text-right space-x-2 mx-4 lg:mr-40">
      <%= link_to "https://github.com/Itok1000/birthnation", class: "h-12 w-12 hover:no-underline", target: "_blank" do %>
        <i class="fa-brands fa-square-github fa-xl" style="color: #ffffff;"></i>
      <% end %>
      <%= link_to "https://x.com/Itoken1000", class: "hover:no-underline", target: "_blank" do %>
        <i class="fa-brands fa-square-x-twitter fa-xl" style="color: #ffffff;"></i>
      <% end %>
     </div>
     <div class="absolute left-1/2 transform -translate-x-1/2 items-center">
      <p class="text-white text-center text-2xl m-0">© 2024 Itok1000</p>
     </div>
    </footer>
</body>
</html>

app/views/shared/_header.html.erb
<body>
    <header class="bg-rose-200 h-12 text-white text-2xl flex items-center">
        <%= link_to "BirthNation", root_path, class: "text-left ml-4" %>
        <div class='ms-auto relative'>
            <div class="dropdown dropdown-end">
                <button class="text-white nav-link focus:outline-none">
                    Menu
                </button>
                <ul tabindex="0" class="dropdown-content menu bg-rose-300 rounded-box z-[1] w-52 p-2 shadow">
                  <%= link_to 'プライバシーポリシー', privacy_path, class: "nav-link" %>
                  <%= link_to '利用規約', terms_path, class: 'nav-link' %>
                  <%= link_to 'お問い合わせ', "https://docs.google.com/forms/d/e/1FAIpQLSe4j07TM5DyfzYTiqFXxpx1I_r52j8NChzN76UqDFLPBYsucQ/viewform?embedded=true", class: 'width="640" height="829" frameborder="0" marginheight="0" marginwidth="0"' %>
                </ul>
            </div>
        </div>
    </header>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const dropdownButton = document.querySelector('.dropdown > button');
            const dropdownContent = document.querySelector('.dropdown-content');

            dropdownButton.addEventListener('click', function() {
                dropdownContent.classList.toggle('hidden');
            });
        });
    </script>
</body>

app/views/static_pages/home.html.erb
<div class="text-center">
  <div class="grid place-items-center">
  <br>
    <%= image_tag 'Birth.png', height: '300', width: '300' %>
  </div>
  <br>
  <h1 class="text-secondary">あなたの誕生月日と近い日に生まれた国家を探してみよう！</h1>
  <%= link_to "スタート", new_users_path, class: "btn btn-wide bg-amber-300 hover:bg-red-300 text-white text-xl my-8" %>
</div>

app/views/static_pages/privacy.html.erb
<div class="text-center my-10">
  <div class="grid place-items-center">
    <br>
    <body>
    <h2 class="text-yellow-400 text-4xl text-center my-8">プライバシーポリシー</h2>
     <div class="flex justify-center my-4">
      <div class="rounded-lg border-solid border-white border-4 bg-amber-50 p-6 w-full lg:w-2/5">
       <div class="text-gray-950 leading-loose space-y-12">
        <div class="my-8">
        <h2 class="md:text-3xl text-xl font-bold mb-5"><p>プライバシーポリシー</p><h2>
         <p>お客様から取得する情報</p>
         <p>当社は、お客様から以下の情報を取得します。</p>
         <p>氏名(ニックネームやペンネームも含む)</p>
         <p>当社ウェブサイトの滞在時間、入力履歴、購買履歴等の当社ウェブサイトにおけるお客様の行動履歴</p>
        </div>
        <div class="my-8">
         <h2 class="md:text-3xl text-xl font-bold mb-5"><p>お客様の情報を利用する目的</p></h2>
         <p>当社は、お客様から取得した情報を、以下の目的のために利用します。</p>
         <p>当社サービスに関する登録の受付、お客様の本人確認、認証のため</p>
         <p>お客様の当社サービスの利用履歴を管理するため</p>
         <p>利用料金の決済のため</p>
         <p>当社サービスにおけるお客様の行動履歴を分析し、当社サービスの維持改善に役立てるため</p>
         <p>当社のサービスに関するご案内をするため</p>
         <p>お客様からのお問い合わせに対応するため</p>
         <p>当社の規約や法令に違反する行為に対応するため</p>
         <p>当社サービスの変更、提供中止、終了、契約解除をご連絡するため</p>
         <p>当社規約の変更等を通知するため</p>
         <p>以上の他、当社サービスの提供、維持、保護及び改善のため</p>
        </div>
        <div class="my-8">
         <h2 class="md:text-3xl text-xl font-bold mb-5"><p>安全管理のために講じた措置</p></h2>
         <p>当社が、お客様から取得した情報に関して安全管理のために講じた措置につきましては、末尾記載のお問い合わせ先にご連絡をいただきましたら、法令の定めに従い個別にご回答させていただきます。</p>
        </div>
        <div class="my-8">
         <h2 class="md:text-3xl text-xl font-bold mb-5"><p>第三者提供</p></h2>
         <p>当社は、お客様から取得する情報のうち、個人データ（個人情報保護法第１６条第３項）に該当するものついては、あらかじめお客様の同意を得ずに、第三者（日本国外にある者を含みます。）に提供しません。</p>
         <p>但し、次の場合は除きます。</p>
         <p>個人データの取扱いを外部に委託する場合</p>
         <p>当社や当社サービスが買収された場合</p>
         <p>事業パートナーと共同利用する場合（具体的な共同利用がある場合は、その内容を別途公表します。）</p>
         <p>その他、法律によって合法的に第三者提供が許されている場合</p>
        </div>
        <div class="my-8">
         <h2 class="md:text-3xl text-xl font-bold mb-5"><p>アクセス解析ツール</p></h2>
         <p>当社は、お客様のアクセス解析のために、「Googleアナリティクス」を利用しています。Googleアナリティクスは、トラフィックデータの収集のためにCookieを使用しています。トラフィックデータは匿名で収集されており、個人を特定するものではありません。Cookieを無効にすれば、これらの情報の収集を拒否することができます。詳しくはお使いのブラウザの設定をご確認ください。Googleアナリティクスについて、詳しくは以下からご確認ください。</p>
         <p>https://marketingplatform.google.com/about/analytics/terms/jp/</p>
        </div>
        <div class="my-8">
         <h2 class="md:text-3xl text-xl font-bold mb-5"><p>プライバシーポリシーの変更</p></h2>
         <p>当社は、必要に応じて、このプライバシーポリシーの内容を変更します。この場合、変更後のプライバシーポリシーの施行時期と内容を適切な方法により周知または通知します。</p>
        </div>
        <div class="my-8">
         <h2 class="md:text-3xl text-xl font-bold mb-5"><p>お問い合わせ</p></h2>
         <p>お客様の情報の開示、情報の訂正、利用停止、削除をご希望の場合は、以下のメールアドレスにご連絡ください。</p>
         <p>e-mail</p>
         <p>jiantaiyiteng1@gmail.com</p>
         <p>この場合、必ず、運転免許証のご提示等当社が指定する方法により、ご本人からのご請求であることの確認をさせていただきます。なお、情報の開示請求については、開示の有無に関わらず、ご申請時に一件あたり1,000円の事務手数料を申し受けます。</p>
        </div>
        <div class="my-8">
         <p>事業者の氏名</p>
         <p>伊藤健太</p>
        </div> 
        <div class="my-8">
         <p>事業者の住所</p>
         <p>千葉県千葉市</p>
         <p>2024年11月12日 制定</p>
         <p>2024年12月09日 改定</p>
        </div>
       </div>
      </div>
     </div>
    </body>
  </div>
</div>

app/views/users/new.html.erb
<div class="text-center my-10">
  <div class="grid place-items-center">
    <br>
    <body>
      <h1 class="font-bold text-xl text-red-300 w-full min-w-min">あなたの名前と誕生日を入力してね</h1>
      <%= form_with(scope: :user, url: submit_users_path, method: :post) do |f| %>
        <div class="text-xl my-6 w-600 min-w-min">
          <%= f.label :name, "名前" %><br>
          <%= f.text_field :name, class: "input input-bordered input-warning w-full" %><br>
        </div>
        <div class="text-xl my-6 w-600 min-w-min">
          <%= f.label :birth_month, "誕生月" %>
          <%= f.select :birth_month, (1..12).to_a, class: "select select-warning max-w-xs" %>
          <%= f.label :birth_day, "誕生日" %>
          <%= f.select :birth_day, (1..31).to_a, class: "select select-warning max-w-xs" %>
        </div>
        <%= f.submit "検索する", class: "btn btn-wide bg-yellow-400 hover:bg-red-300 text-white text-xl my-6" %>
      <% end %>
    </body>
  </div>
</div>

app/views/users/result.html.erb
<div class="text-center my-10">
  <div class="grid place-items-center">
    <br>
    <body>
      <p>あなたの名前は <%= @user.name %> です</p>
      <p>誕生日は <%= @user.birth_month %> 月 <%= @user.birth_day %> 日です</p>
      
      <% if @national_day.present? %>
        <h2 class="font-bold text-red-300">あなたの誕生日に近い国の誕生日はこちら</h2>
        <br>
        <p>
          <img src="<%= @national_day.image_url %>"
               class="w-32 h-auto rounded shadow-lg" />
        </p>
        <br>
        <p>国名: <%= @national_day.country_name %></p>
        <p>日付: <%= @national_day.national_day.strftime("%m月%d日") %></p>
        <p>説明: <%= @national_day.description %></p>
        <p>補足: <%= @national_day.remark %></p>
      <% else %>
        <p>あなたの誕生日に近い国の誕生日は見つかりませんでした。</p>
      <% end %>
      <%= link_to "もう一度試す", new_users_path, class: "btn btn-wide bg-cyan-400 hover:bg-orange-300 text-white text-xl my-3" %><br>
      <%= link_to "トップに戻る", root_path, class: "btn btn-wide bg-yellow-400 hover:bg-red-300 text-white text-xl" %>
      <br>
       <p class="font-bold">自分の誕生日と同じ国の記念日をXでみんなに伝えてみよう！</p>
       <br>
      <% if @national_day.present? %>
        <%= link_to "https://twitter.com/share?url=#{request.url}&text=私(#{@user.name})の誕生日(#{@user.birth_month}月#{@user.birth_day}日)に近い国の誕生日は%0a#{@national_day.country_name}の#{@national_day.description}です！%0a%23BirthNation%0a%23建国記念の日%0a%23HBD%0a",
          target: '_blank',
          class: "btn btn-outline inline-flex items-center space-x-2" do %>
          <i class="fa-brands fa-x-twitter inline-block hover:text-white"></i>シェア
        <% end %>
      <% else %>
        <%= link_to "https://twitter.com/share?url=#{request.url}&text=私(#{@user.name})の誕生日(#{@user.birth_month}月#{@user.birth_day}日)に近い国の誕生日は見つかりませんでした！%0a%23BirthNation%0a%23建国記念の日%0a%23HBD%0a",
          target: '_blank',
          class: "btn btn-outline inline-flex items-center space-x-2" do %>
          <i class="fa-brands fa-x-twitter inline-block hover:text-white"></i>シェア
        <% end %>
      <% end %>            
    </body>
  </div>
</div>